import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Layout } from "../../components/Layout";
import styles from "../../styles/Home.module.css";

const Details: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}></main>
      </Layout>
    </div>
  );
};

export default Details;
